# Generated by Django 4.1.1 on 2022-09-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="passworrd",
            field=models.CharField(max_length=200),
        ),
    ]
