# Generated by Django 4.1.1 on 2022-09-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0002_alter_post_passworrd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="passworrd",
            new_name="password",
        ),
    ]
